[env:nicenano]
platform = nordicnrf52
board = nicenano
framework = arduino
monitor_speed = 115200
upload_protocol = nrfutil


; 1. Tells PlatformIO to scan ALL files (including framework files) for dependencies
lib_ldf_mode = deep

; 2. Prevents libraries from being "archived" into static .a files. 
;    This forces proper linking so the Core can see TinyUSB.
lib_archive = no
lib_ignore = zlib,miniz

; 3. Setup USB Serial
monitor_dtr = 1
monitor_rts = 1
build_flags = 
    -DUSBCON
    -DUSE_TINYUSB
    -DZ_SOLO
    -DARDUINO_USB_CDC_ON_BOOT=1 

; 4. Dependencies
lib_deps =
    adafruit/Adafruit TinyUSB Library
    zinggjm/GxEPD2
    adafruit/Adafruit GFX Library
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    mikalhart/TinyGPSPlus
    Wire